name: Deploy Application

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    outputs:
      DEPLOY_DOMAIN: ${{ steps.set-env.outputs.DEPLOY_DOMAIN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Set environment variables
        id: set-env
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "DEPLOY_DOMAIN=auroville.social" >> $GITHUB_OUTPUT
            echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> $GITHUB_ENV
            echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> $GITHUB_ENV
          else
            echo "DEPLOY_DOMAIN=staging.auroville.social" >> $GITHUB_OUTPUT
            echo "SUPABASE_URL=${{ secrets.STAGING_SUPABASE_URL }}" >> $GITHUB_ENV
            echo "SUPABASE_ANON_KEY=${{ secrets.STAGING_SUPABASE_ANON_KEY }}" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npx tsc --noEmit

      - name: Lint check
        run: npm run lint

      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ env.SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ env.SUPABASE_ANON_KEY }}

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        if: github.event_name == 'push'
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/auronet:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/auronet:${{ github.ref_name }}
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ env.SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ env.SUPABASE_ANON_KEY }}

  deploy:
    needs: test-and-build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    env:
      DEPLOY_PATH: /opt/auronet
      DEPLOY_DOMAIN: ${{ needs.test-and-build.outputs.DEPLOY_DOMAIN }}
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.DEPLOY_PATH }}

            # Create branch-specific docker-compose file
            cat > docker-compose.${{ github.ref_name }}.yml <<EOL
            version: '3.9'
            services:
              auronet-${{ github.ref_name }}:
                image: ${{ secrets.DOCKER_USERNAME }}/auronet:${{ github.ref_name }}
                environment:
                  - DATABASE_URL=${{ github.ref == 'refs/heads/main' && secrets.DATABASE_URL || secrets.STAGING_DATABASE_URL }}
                  - NEXT_PUBLIC_SUPABASE_URL=${{ github.ref == 'refs/heads/main' && secrets.SUPABASE_URL || secrets.STAGING_SUPABASE_URL }}
                  - NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ github.ref == 'refs/heads/main' && secrets.SUPABASE_ANON_KEY || secrets.STAGING_SUPABASE_ANON_KEY }}
                  - SUPABASE_SERVICE_ROLE_KEY=${{ github.ref == 'refs/heads/main' && secrets.SUPABASE_SERVICE_ROLE_KEY || secrets.STAGING_SUPABASE_SERVICE_ROLE_KEY }}
                  - NODE_ENV=production
                healthcheck:
                  test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
                  interval: 10s
                  timeout: 10s
                  retries: 3
                  start_period: 30s
                labels:
                  - "traefik.enable=true"
                  - "traefik.http.routers.${{ github.ref_name }}-secure.rule=Host(\`${{ env.DEPLOY_DOMAIN }}\`)"
                  - "traefik.http.routers.${{ github.ref_name }}-secure.entrypoints=websecure"
                  - "traefik.http.routers.${{ github.ref_name }}-secure.tls=true"
                  - "traefik.http.services.${{ github.ref_name }}.loadbalancer.server.port=3000"
                networks:
                  - web
            networks:
              web:
                external: true
            EOL

            # Pull latest image and deploy
            docker pull ${{ secrets.DOCKER_USERNAME }}/auronet:${{ github.ref_name }}
            docker compose -f docker-compose.${{ github.ref_name }}.yml up -d --force-recreate
