            ${{ secrets.DOCKER_USERNAME }}/auronet:latest
            ${{ secrets.DOCKER_USERNAME }}/auronet:main
          # Enable cache like staging
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/auronet:main-cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/auronet:main-cache,mode=max
          build-args: |
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}
